channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - kallisto = 0.46.2
  - bbmap = 38.90
  - cutadapt = 3.2
  - trimmomatic = 0.36
  - fastqc = 0.11.8
  - multiqc = 1.6
  - r-tidyverse = 1.3.0
  - bioconductor-deseq2 = 1.30.0
  - bioconductor-tximport = 1.18.0
  - r-stringr = 1.4.0
  - r-magrittr = 1.5
  - r-pheatmap = 1.0.12
  - r-ggplot2 = 3.3.3
  - bioconductor-biomart = 2.46.0
  - bioconductor-org.at.tair.db = 3.12.0
  - bioconductor-clusterprofiler = 3.18.0
  - bioconductor-fgsea = 1.16.0
  - r-cowplot = 1.1.1
